services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network
    command: ["npm", "run", "start"]

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
